import{S as w,i as l,a as S}from"./assets/vendor-DFCQGEf1.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const i of r.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&n(i)}).observe(document,{childList:!0,subtree:!0});function o(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function n(e){if(e.ep)return;e.ep=!0;const r=o(e);fetch(e.href,r)}})();const P="50099197-cf66e6150e6b3edf0d1a830a4",q="https://pixabay.com/api/",h=40;let a=1,c="",f=0;const E=document.querySelector("#search-form"),A=document.querySelector('input[name="searchQuery"]'),d=document.querySelector(".gallery"),m=document.querySelector(".loader"),u=document.querySelector(".load-more");let g=new w(".gallery a");E.addEventListener("submit",async t=>{if(t.preventDefault(),c=A.value.trim(),!!c){a=1,d.innerHTML="",u.classList.add("hidden"),p(!0);try{const{hits:s,totalHits:o}=await y(c,a);f=o,s.length===0?l.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"}):(v(s),g.refresh(),f>h&&d.children.length>0&&u.classList.remove("hidden"))}catch{l.error({message:"An error occurred while fetching images.",position:"topRight"})}finally{p(!1)}}});u.addEventListener("click",async()=>{a++,p(!0);try{const{hits:t}=await y(c,a);v(t),g.refresh(),R(),a*h>=f&&(u.classList.add("hidden"),l.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"}))}catch{l.error({message:"An error occurred while loading more images.",position:"topRight"})}finally{p(!1)}});async function y(t,s){return(await S.get(q,{params:{key:P,q:t,image_type:"photo",orientation:"horizontal",safesearch:!0,page:s,per_page:h}})).data}function v(t){const s=t.map(({webformatURL:o,largeImageURL:n,tags:e,likes:r,views:i,comments:L,downloads:b})=>`
    <div class="photo-card">
      <a href="${n}">
        <img src="${o}" alt="${e}" loading="lazy" />
      </a>
      <div class="info">
        <div><p class="label">Likes</p><p class="value">${r}</p></div>
        <div><p class="label">Views</p><p class="value">${i}</p></div>
        <div><p class="label">Comments</p><p class="value">${L}</p></div>
        <div><p class="label">Downloads</p><p class="value">${b}</p></div>
      </div>
    </div>`).join("");d.insertAdjacentHTML("beforeend",s)}function p(t){t?m.classList.remove("hidden"):m.classList.add("hidden")}function R(){const{height:t}=d.firstElementChild.getBoundingClientRect();window.scrollBy({top:t*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
